---
- name: "Authenticate with OME API"
  uri:
    url: "{{ ome_console_url }}{{ ome_api_base }}{{ ome_endpoints.sessions }}"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      UserName: "{{ ome_username }}"
      Password: "{{ ome_password }}"
      SessionType: "API"
    validate_certs: "{{ ome_validate_certs }}"
    timeout: "{{ ome_timeout }}"
    status_code: [200, 201]
  register: ome_auth_response
  no_log: true

- name: "Extract OME session token"
  set_fact:
    ome_session_token: "{{ ome_auth_response.json.SessionToken }}"
    ome_session_id: "{{ ome_auth_response.json.Id }}"
  no_log: true

- name: "Verify OME authentication"
  fail:
    msg: "Failed to authenticate with OME API"
  when: ome_session_token is not defined
