---
- name: "Transform OME data to SunBird format"
  set_fact:
    sunbird_devices: []

- name: "Process each server with inventory"
  include_tasks: transform_single_device.yml
  loop: "{{ all_server_inventory }}"
  loop_control:
    loop_var: device_with_inventory
    label: "{{ device_with_inventory[0].DeviceName }}"

- name: "Display transformation summary"
  debug:
    msg: "Successfully transformed {{ sunbird_devices | length }} devices for SunBird sync"
